### ISSUE TITLE
[UI] Widget Container

### ISSUE THREAD

**Issue by peculiarity** [OasisDEX/oasis-react#10]
Create common widget container that will embed the views of all widgets 

- Market
- Chart
- New Buy / Sell Order
- Buy/ Sell Orderbooks
- My Open / Closed Orders
- Market History 
- Token Balance
- Wrap / Unwrap 
- Wrap / Unwrap History
- Transfer 
- Transfer History

**Comment by deepinit-arek** [comment]
@peculiarity How would it differ from OasisApp root component?
