### ISSUE TITLE
Generate currency pairs for Market Widget

### ISSUE THREAD

**Issue by peculiarity** [OasisDEX/oasis-react#11]
Generate currency pairs.

 **Things to consider**: Does the order matter? ( MKR / W-ETH  and W-ETH / MKR ). 
@pimato  Can you write your comment please?

For each pair we must have  corresponding volume.
For now the volume is based on the quote ( the amount of the _quote currency_ is accumulated into a single variable ).

There was discussion that it would be better this value to be generated from the _base currency_ 

@pimato Would be nice to elaborate on this. I spoke with @nik who spoke with @equivrel.

The pairs should be **sortable**.

There are top 3 pairs which should remain in their order as specified:

1. MKR / W-ETH
2. W-ETH / SAI
3. MKR / SAI

Everything else should be sorted by volume  - _descending_ .

Hint: Right now it's implemented with given priority for each pair. First one has priority **10** , second one **9** and third one **8**. All other orders have priority **1**. So I sorted them by priority in a descending way and then I apply the volume sorting. 

This solution is not very good because what if I must have  20 items with different priority and the top 3 pairs should be always on top. I must change their priority as well.  

Feel free to propose a better solution

**Comment by pimato** [comment]
what is the reason to go with the base currency to indicate the volume ?

**Comment by peculiarity** [comment]
@pimato I had conversation with @nik who had conversation with @equivrel. Better discuss it with them
