### ISSUE TITLE
Create expandable table of all currency pairs

### ISSUE THREAD

**Issue by peculiarity** [OasisDEX/oasis-react#12]
The currencies should be visualized in  a table.

By default the pairs with monthly volume should be visible only. 

There are top 3 pairs that should be **ALWAYS VISIBLE** ( even without volume ). 
The amount of volume shouldn't affect the order of those 3 pairs.

From top to bottom:
1. MKR / W-ETH
2. W-ETH / SAI
3. MKR / SAI

There should be **SHOW MORE / LESS** button.

Show more displays other pairs that has no volume.
Show less hides the pairs without volume ( except the top 3 pairs )

**Comment by deepinit-arek** [comment]
@peculiarity But is this really sortable? I thnik its more like expandable
