### ISSUE TITLE
Change pair from the URL

### ISSUE THREAD

**Issue by peculiarity** [OasisDEX/oasis-react#15]
1. When the user enters the URL without any pair , there should be a default one loaded **( MKR / W-ETH )**
2. When the user enters non-existing pair, the default one should be loaded.
3. When the use enters an existing one, this should act like a pair has been selected from the _ Market Widget _ .
4. If we have **MKR / W-ETH**  but the user enters **W-ETH / MKR** we have to either load as it's **MKR / W-ETH** or we have to act as a separate pair. 

@pimato Again please verify this behavior

**Comment by pimato** [comment]
agreed on all points except for 4). It should load the **MKR / W-ETH** pair.
