### ISSUE TITLE
Closing message boards

### ISSUE THREAD

**Issue by peculiarity** [OasisDEX/oasis-react#18]
Given the two message boards we have right now: 
 - _GET STARTED_
 - _WARNINGS_

![image](https://user-images.githubusercontent.com/23715025/33605364-b88a0f54-d9b9-11e7-9a98-dec62f35fdeb.png)

What should be the behavior if the user click on the _x_ button.

**Scenario 1:** We remove (close) them only for the session and next time the user enters he will see them again.
**Scenario 1:** We remove them from now on for the given browser and once the user has removed ( closed ) them he won't see them on any following session. ( using localStorage )

@pimato - What should be the behavior?

**Comment by pimato** [comment]
there is even a third scenario: Only the get started message is getting saved as removed. The Warning sign should always be there because it is new tech, and funds could always be stolen.

**Comment by deepinit-arek** [comment]
@peculiarity @pimato I think we should go with *third scenario* for now.

**Comment by deepinit-arek** [comment]
This also includes persitable session
