### ISSUE TITLE
Buy/Sell modal redesign for the new allowance approach

### ISSUE THREAD

**Issue by pimato** [OasisDEX/oasis-react#46]
Hey guys,

I finally had some time the last days to do some work for the new Allowance designs:

**new**:

- Allowance balance removed
- User can inform itself by using the dropdown to get informations about the new allowance.
- User now only get one buy/sell modal (in the past, two modals for buying and setting the allowance)
- User is only enabling the token, no defining of any number needed
- User can see how long his transaction is taking with 
    - a timer
    - with a link of his transaction
    - confirmation counter

**left**:
User who never enabled the token is

**middle**: 
User who clicked on the enable button

**right**:
User who clicked on the dropdown Icon to get some more information why he actually needs to enable the token for trading.

![modal](https://user-images.githubusercontent.com/5337809/34376134-87bfa68a-eaea-11e7-9685-fbb6b1c4c659.png)

**Question**:

do we need display the status (confirmation number) of the transaction actually as a text? I think we could remove it and use an "confirmed" icon to indicate a transaction confirmation.

What do you think in general about the design?

**Comment by peculiarity** [comment]
I like the design  very much.
Afaik `0x` api allows you to do this as well by setting very high number for the allowance. I guess we  can do that in this way as well.

**Comment by pimato** [comment]
I have updated the new allowance approach:

![all](https://user-images.githubusercontent.com/5337809/34419521-a5b950ee-ec04-11e7-8753-13563e0cc389.png)

**Changes:**

- replaced the `order matching status` with the `trading of (TOKEN) status`
- replaced the confirmation text with a simple tick icon
- added a scenario where the transaction can fail.

**Comment by pimato** [comment]
## Order Modal with token trading disabled

![order-token-disabled](https://user-images.githubusercontent.com/5337809/34419569-e8be3896-ec04-11e7-933b-ae39930b0b46.png)

**measurements**: [measures.zip](https://github.com/OasisDEX/oasis-react/files/1591846/measures.zip)
**dropdown icon:** [ic_keyboard_arrow_down_black_24px.svg.zip](https://github.com/OasisDEX/oasis-react/files/1591850/ic_keyboard_arrow_down_black_24px.svg.zip)

**Comment by pimato** [comment]
## Order Modal with transaction sent

![order-token-transaction-send](https://user-images.githubusercontent.com/5337809/34419923-cb8d368a-ec06-11e7-8bdd-1dbb5d9c4325.png)

**measurements**: [order-transaction-out.zip](https://github.com/OasisDEX/oasis-react/files/1591867/order-transaction-out.zip)

**dropdown icon:** [ic_keyboard_arrow_down_black_24px.svg.zip](https://github.com/OasisDEX/oasis-react/files/1591850/ic_keyboard_arrow_down_black_24px.svg.zip)
**loading icon:** [loading.svg.zip](https://github.com/OasisDEX/oasis-react/files/1591875/loading.svg.zip)

**Comment by pimato** [comment]
## Order Modal with transaction confirmed

![confirmed](https://user-images.githubusercontent.com/5337809/34420277-0545147c-ec09-11e7-8d07-e6b415c8ce53.png)

**measurements**: [order-transaction-confirmed.zip](https://github.com/OasisDEX/oasis-react/files/1591891/order-transaction-confirmed.zip)
**confirmed icon**:  [icon-transaction-confirmed.svg.zip](https://github.com/OasisDEX/oasis-react/files/1591893/icon-transaction-confirmed.svg.zip)

**Comment by pimato** [comment]
## Order Modal with transaction failed

![order-transaction-failed](https://user-images.githubusercontent.com/5337809/34420468-f862f930-ec09-11e7-9f15-740f7a8fa9b5.png)

**measurements**: [order-transaction-failed.zip](https://github.com/OasisDEX/oasis-react/files/1591899/order-transaction-failed.zip)
**failed icon**:  
[icon-transaction-failed.svg.zip](https://github.com/OasisDEX/oasis-react/files/1591901/icon-transaction-failed.svg.zip)

**Comment by pimato** [comment]
## Order Modal dropdown open

![order-token-disabled copy 3](https://user-images.githubusercontent.com/5337809/34420756-8d36f696-ec0b-11e7-9e04-0b093aa3cad6.png)

**measurements**: [order-token-enable-drop.zip](https://github.com/OasisDEX/oasis-react/files/1591921/order-token-enable-drop.zip)
**enable shield icon**: [icon-token-enable.svg.zip](https://github.com/OasisDEX/oasis-react/files/1591922/icon-token-enable.svg.zip)
